# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sm_id', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField()),
                ('updated_by', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SmDataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_id', models.CharField(max_length=200, unique=True)),
                ('provided_name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('provided_description', models.CharField(max_length=200)),
                ('data_source_type', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('sentiment_enabled', models.BooleanField(default=False)),
                ('elevated_access', models.BooleanField(default=False)),
                ('canonical_id', models.IntegerField(default=0)),
                ('sm_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyticsApi.SmAccount')),
            ],
        ),
        migrations.CreateModel(
            name='SmDataSourceFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.CharField(max_length=200, unique=True)),
                ('feature_type', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('available_start_time', models.DateTimeField()),
                ('available_end_time', models.DateTimeField()),
                ('requested_start_time', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('sm_data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyticsApi.SmDataSource')),
            ],
        ),
    ]
