# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smaccount',
            name='account_utilization',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='smaccount',
            name='image_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
